apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlabdata-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain    
  nfs:
    server: 192.168.10.40
    path: /pv/gitlabdata
    readOnly: false
