apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm_template.name" . }}
  namespace: {{ include "helm_template.name" . }}
  labels:
    {{- include "helm_template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ template "getAppPort" . }}
      targetPort: {{ template "getAppPort" .}}
  selector:
    {{- include "helm_template.selectorLabels" . | nindent 4 }}
