{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm_template.serviceAccountName" . }}
  namespace: {{ .Values.namespaceOverride | default "default" }}
  labels:
    {{- include "helm_template.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
